name: ecobici_automl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas=2.1.4
  - scikit-learn=1.3.2
  - matplotlib=3.7.2
  - scipy=1.11.4
  - joblib=1.3.2
  - jupyterlab
  - pyarrow
  - lightgbm
  - xgboost=1.7.6
  - graphviz
  - python-graphviz
  - pip:
      - pycaret==3.3.2
      - flaml==2.1.1
      - mlflow==2.14.2
      - protobuf==4.25.3
      - werkzeug==3.1.1
      - setuptools<81