# =====================================================
# 🧩 CONFIGURACIÓN — ECOBICI-AUTOML
# =====================================================

project:
  name: "Ecobici-AutoML"
  version: "1.0.0"
  author: "R. Inza"
  description: "Predicción de disponibilidad de bicicletas en Ecobici (Buenos Aires)."

runtime:
  use_gpu: false
  log_level: "INFO"
  mlflow_tracking_uri: "mlruns"

paths:
  raw_dir: "data/raw"
  features_in: "data/raw/status_clean.parquet"
  curated_file: "data/curated/ecobici_model_ready.parquet"
  stations_file: "data/curated/station_information.parquet"
  splits_dir: "data/splits"
  train_split: "data/splits/train.parquet"
  val_split: "data/splits/val.parquet"
  test_split: "data/splits/test.parquet"
  models_dir: "models"
  mlruns_dir: "mlruns"
  predictions_dir: "predictions"
  tiles_dir: "tiles"
  reports_dir: "reports"
  logs_dir: "reports/logs"

data:
  target: "num_bikes_available"
  id_col: "station_id"
  ts_col: "ts_local"

training:
  metric: "RMSE"
  optimize: true
  random_state: 42
  test_size: 0.2

backtest:
  horizons: [1, 3, 6, 12]

inference:
  horizons: [1, 3, 6, 12]
  asof: "2025-10-26 18:00:00"

registry:
  compare_metric: "RMSE"
  promote_if_better: true
  champion_path: "models/Champion/best_model.pkl"

pycaret:
  experiment_name: "ecobici_pycaret"

flaml:
  time_budget_sec: 600
  refine_time_sec: 120
  experiment: "ecobici_automl_flaml"

automl:
  framework: "both"        # pycaret | flaml | both
  tune: true               # (solo PyCaret)
  tune_iters: 50
  metric: "RMSE"
  folds: 3

retrain:
  mode: "curated"          # trainval | curated

prediction_mode: "slots"
slots: ["09:00","13:00","16:00","20:00"]
lead_minutes: 10 