paths:
  # Si vas a trabajar con un único archivo preparado con ts:
  raw_glob: "data/ecobici_station_status_with_ts.parquet"
  # O, si más adelante sumás snapshots, cambiá por: "data/*.parquet"

  curated: "data/curated/ecobici_timeseries.parquet"
  training_dir: "data/training"
  models_dir: "models"

prepare:                # usado por src/prepare_from_parquet.py
  emit_train: true
  horizons: [10, 20]    # los que ya generaste: train_10min / train_20min
  tz_local: "America/Argentina/Buenos_Aires"

train:                  # usado por src/train_model.py
  target_prefix: "target_bikes_t+"
  default_horizon: 10   # usa train_10min.parquet por defecto
  session_id: 123
  use_gpu: false
  log_experiment: false
  n_select: 10          # cantidad de modelos a comparar (compare_models)

app:                    # reservado para la app (futuro)
  default_horizon: 10