# =====================================================
# 🧩 CONFIGURACIÓN BÁSICA — ECOBICI AUTOML
# =====================================================

project:
  name: "Ecobici-AutoML"
  version: "0.1.0"
  author: "R. Inza"
  description: "Predicción de disponibilidad de bicicletas en el sistema Ecobici (BA)."

paths:
  data_raw: "data/raw/"
  data_interim: "data/interim/"
  data_curated: "data/curated/"
  outputs: "outputs/"
  models: "models/"
  reports: "reports/"
  logs: "logs.log"

modeling:
  target: "num_bikes_available"
  horizon_hours: [1, 3, 6, 12]
  test_size: 0.2
  random_state: 42

automl:
  frameworks: ["pycaret", "h2o", "flaml"]
  metric: "RMSE"
  optimize: true

runtime:
  use_gpu: false
  mlflow_tracking_uri: "mlruns/"